#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# We want to remove php images that are not used by any php-fpm containers.
# We use `podman rmi` to remove images, ignoring errors if they are in use.
# Images with dual tags will not be removed (they are in use by the php-fpm service)

for img_id in $(podman images --quiet --filter=reference='ghcr.io/nethserver/php*-fpm:*'); do
    # try to remove the image, ignoring errors if it's in use
    podman rmi "$img_id" 2>/dev/null
done

# With the change from bitnami images to official images, we have some old bitnami images (with dual tags)
# that are not used anymore. We can remove them by filtering with the "bitnami" repository.
# This is safe because we are sure that the current ns8 module does not use bitnami images.
# bitnami was used with webserver:1.1.2 and earlier.
for img_id in $(podman images --quiet --filter=reference='docker.io/bitnami/php-fpm:*'); do
    podman rmi -f "$img_id"
done
