name: Test module
# The run belongs to the default branch under workflow_run: name the tested one.
run-name: "Test ${{ github.event.workflow_run.head_branch || github.ref_name }} on QEMU"

on:
  workflow_dispatch:
    inputs:
      debug_shell:
        description: "Debug shell"
        required: true
        type: boolean
  workflow_run:
    workflows: ["Publish images"]
    types: [completed]

jobs:
  run_tests:
    uses: NethServer/ns8-github-actions/.github/workflows/test-module-qemu.yml@v1
    with:
      debug_shell: ${{ github.event.inputs.debug_shell == 'true' || false }}
      # Other inputs: https://github.com/NethServer/ns8-github-actions/blob/v1/docs/test-module-qemu.md#inputs
